@startuml
class application.shop.actions.forge.ForgeLeaderUnitCard {
+ LeaderUnitCard runForge()
}

class student.TestBuffSpellCard {
~ void testCastSpell()
~ void testPowerIncreaseLimits()
}

class deck.RemoveCardFailedException {
- {static} long serialVersionUID
+ String message
}

class application.shop.actions.ReviewDeckList {
- Player player
- List<Card> cards
+ void run()
}


class student.TestDebuffUnitCard {
~ void testSetDebuffPower()
~ void testAttack()
}

class application.base.CLIApp {
# PrintStream out
# Scanner in
# int getChoice(int,int,Runnable)
# int getChoice(int,int,boolean,Runnable)
# int getChoice(int,int,Runnable,Function<Integer,String>)
# int getChoice(int,int,boolean,Runnable,Function<Integer,String>)
~ boolean ensureSelection(int)
~ boolean ensureSelection(int,Function<Integer,String>)
}


class student.TestNormalUnitCard {
~ void testConstructor()
~ void testNonPositiveConstructor()
~ void testAttack()
}

class application.shop.actions.ForgeCard {
+ Card runForge()
+ void promptItemType()
}

class card.type.VenomUnitCard {
+ int attackUnit(UnitCard)
+ int dead(Player)
}

class student.TestDeck {
~ void testInsertCardAndRemoveCard()
~ void testRemoveCard()
~ void testRemoveNonExsistanceCard()
}

class student.TestVenomUnitCard {
~ void testAttackAndDead()
}

class application.shop.actions.PlayTest {
~ Player[] opponentList
- Player player
- Player opponent
- UnitCard[] playerField
- UnitCard[] enemyField
- List<Card> playerHand
- boolean playerWincondition
+ void run()
~ int winConCheck()
~ void DrawCard(int)
~ void UseCard()
+ void prompt_ChooseOppo()
+ void prompt_ChooseHandCard()
+ void prompt_UnitCardBloodCost(int,int)
+ void prompt_SpellCardBloodCost(int,int)
+ void prompt_PlayUnitCard()
+ void prompt_SpellCard(boolean,int)
~ {static} Deck shuffleArray(Deck)
~ void Attack_Phase()
~ void OpponentAttack_Phase()
~ void printGameStatus()
~ void printBoardStatus()
~ String printCardNameOnBoard(boolean,int)
~ String printCardStatOnBoard(boolean,int)
}


class card.type.NormalUnitCard {
+ int attackUnit(UnitCard)
}

class player.Player {
- String name
- int currentDamagePoint
- Deck deck
+ String toString()
+ String toStringShortVer()
+ String getName()
+ void takeDamage(int)
+ void resetHealth()
+ Deck getDeck()
+ void setDeck(Deck)
+ int getCurrentDamagePoint()
+ void setCurrentDamagePoint(int)
}


class application.shop.actions.ChangeToPremadeDeck {
- Player player
+ void run()
+ void prompt()
}


class application.ShopApp {
+ Card getCardChoice(List<Card>,Runnable)
+ Card getCardChoice(Card[],Runnable)
+ Deck getDeckChoice(List<Deck>,Runnable)
}

class application.shop.actions.forge.ForgeVenomUnitCard {
+ VenomUnitCard runForge()
}

class application.shop.actions.forge.ForgeBuffSpellCard {
+ BuffSpellCard runForge()
+ void promptSpellSpeed()
}

class application.shop.actions.RemoveCard {
- Player player
- List<Card> cards
+ void run()
+ void prompt()
}


class card.type.LeaderUnitCard {
- int buffPower
- int buffHealth
+ int attackUnit(UnitCard)
+ void buffUnit(UnitCard[])
+ int getBuffPower()
+ void setBuffPower(int)
+ int getBuffHealth()
+ void setBuffHealth(int)
+ String toString()
}


class application.shop.Shop {
~ Player player
~ List<Card> cards
+ void run()
+ void prompt()
}


class student.TestLeaderUnitCard {
~ void testBuffUnit()
~ void testAttack()
}

class card.type.BuffSpellCard {
- int powerIncrease
+ void castSpell(UnitCard)
+ int getPowerIncrease()
+ void setPowerIncrease(int)
}


class application.shop.actions.forge.ForgeDebuffUnitCard {
+ DebuffUnitCard runForge()
}

class student.TestDamageSpellCard {
~ void testCastSpell()
~ void testSetDamageLimits()
}

class deck.Deck {
- String name
- int deckSize
- Card[] deckList
+ int insertCard(Card)
+ Card removeCard(int)
+ String toString()
+ Card[] getDeckList()
+ String getName()
+ int getDeckSize()
+ void setDeckSize(int)
}


class application.shop.actions.forge.ForgeDamageSpellCard {
+ DamageSpellCard runForge()
+ void promptSpellSpeed()
}

class deck.PremadeDeck {
~ {static} LeaderUnitCard darius
~ {static} LeaderUnitCard ezreal
~ {static} LeaderUnitCard braum
~ {static} NormalUnitCard cat
~ {static} NormalUnitCard dog
~ {static} NormalUnitCard bird
~ {static} NormalUnitCard log
~ {static} VenomUnitCard poisonFlower
~ {static} BuffSpellCard potion
~ {static} DamageSpellCard arrow
~ {static} NormalUnitCard fighter
~ {static} NormalUnitCard blackRose
~ {static} NormalUnitCard solider
~ {static} DebuffUnitCard iceWitch
~ {static} DebuffUnitCard iceWolf
~ {static} VenomUnitCard madDoc
~ {static} BuffSpellCard hiPotion
~ {static} BuffSpellCard fastPotion
~ {static} DamageSpellCard superArrow
~ {static} DamageSpellCard gun
~ {static} NormalUnitCard minotaur
~ {static} NormalUnitCard warrior
~ {static} NormalUnitCard guardian
~ {static} DebuffUnitCard iceWizard
~ {static} DebuffUnitCard iceBear
~ {static} VenomUnitCard experi
~ {static} BuffSpellCard megaPotion
~ {static} DamageSpellCard cannon
+ {static} List<Card> initialCardStock
~ {static} Card[] defaultD
~ {static} Card[] noxasD
~ {static} Card[] PnZD
~ {static} Card[] freljordD
~ {static} Deck defaultDeck
~ {static} Deck noxasDeck
~ {static} Deck arcaneDeck
~ {static} Deck freljordDeck
~ {static} NormalUnitCard cat1
~ {static} NormalUnitCard cat2
~ {static} NormalUnitCard log1
~ {static} UnitCard[] voidField
~ {static} UnitCard[] catField
~ {static} UnitCard[] treeField
~ {static} UnitCard[] forestField
~ {static} UnitCard[] noxasField
~ {static} UnitCard[] freljordField
~ {static} UnitCard[] arcaneField
+ {static} Deck[] premadeDecks
+ {static} UnitCard[][] premadeField
}

class deck.InsertCardFailedException {
- {static} long serialVersionUID
+ String message
}

class application.shop.actions.forge.ForgeNormalUnitCard {
+ NormalUnitCard runForge()
}

abstract class card.base.Card {
- String name
- String flavorText
- int bloodCost
+ {abstract}String toString()
+ String getName()
+ void setName(String)
+ String getFlavorText()
+ void setFlavorText(String)
+ int getBloodCost()
+ void setBloodCost(int)
+ boolean equals(UnitCard)
+ Object clone()
}


class application.shop.actions.InsertCard {
- Player player
- List<Card> cards
+ void run()
+ void prompt()
}


class card.type.DebuffUnitCard {
- int debuffPower
+ int attackUnit(UnitCard)
+ int getDebuffPower()
+ void setDebuffPower(int)
}


abstract class card.base.SpellCard {
- boolean isBurstSpeed
+ String toString()
+ {abstract}void castSpell(UnitCard)
+ boolean isBurstSpeed()
+ void setIsBurstSpeed(boolean)
}


class application.Main {
~ {static} Scanner scanner
- {static} void printLineSeparator()
- {static} void printDeckList(Deck)
+ {static} void main(String[])
}


abstract class card.base.UnitCard {
- int power
- int health
+ {abstract}int attackUnit(UnitCard)
+ int attackPlayer(Player)
+ String toString()
+ int getPower()
+ void setPower(int)
+ int getHealth()
+ void setHealth(int)
}


class progmeth_2025_1.Main {
+ {static} void main(String[])
}

class application.PlayerSelection {
+ Deck runDeckSelection()
+ Deck runOpponentDeckSelection()
- void printDecks()
}

class card.type.DamageSpellCard {
- int damage
+ void castSpell(UnitCard)
+ int getDamage()
+ void setDamage(int)
}




application.ShopApp <|-- application.shop.actions.forge.ForgeLeaderUnitCard
deck.Exception <|-- deck.RemoveCardFailedException
application.ShopApp <|-- application.shop.actions.ReviewDeckList
application.ShopApp <|-- application.shop.actions.ForgeCard
card.base.UnitCard <|-- card.type.VenomUnitCard
application.ShopApp <|-- application.shop.actions.PlayTest
card.base.UnitCard <|-- card.type.NormalUnitCard
application.ShopApp <|-- application.shop.actions.ChangeToPremadeDeck
application.base.CLIApp <|-- application.ShopApp
application.ShopApp <|-- application.shop.actions.forge.ForgeVenomUnitCard
application.ShopApp <|-- application.shop.actions.forge.ForgeBuffSpellCard
application.ShopApp <|-- application.shop.actions.RemoveCard
card.base.UnitCard <|-- card.type.LeaderUnitCard
application.ShopApp <|-- application.shop.Shop
card.base.SpellCard <|-- card.type.BuffSpellCard
application.ShopApp <|-- application.shop.actions.forge.ForgeDebuffUnitCard
application.ShopApp <|-- application.shop.actions.forge.ForgeDamageSpellCard
deck.Exception <|-- deck.InsertCardFailedException
application.ShopApp <|-- application.shop.actions.forge.ForgeNormalUnitCard
card.base.Cloneable <|.. card.base.Card
application.ShopApp <|-- application.shop.actions.InsertCard
card.base.UnitCard <|-- card.type.DebuffUnitCard
card.base.Card <|-- card.base.SpellCard
card.base.Card <|-- card.base.UnitCard
application.ShopApp <|-- application.PlayerSelection
card.base.SpellCard <|-- card.type.DamageSpellCard
@enduml